### ISSUE TITLE
こちらにProtoSpaceのURLを貼り付けてください。

### ISSUE THREAD

**Issue by MakiTaka** [nakajiman7/protospace-31551#3]

**Comment by nakajiman7** [comment]
https://protospace-31551.herokuapp.com/

宜しくお願いいたします。

**Comment by MakiTaka** [comment]
@nakajiman7 さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]
・編集ページで編集するとエラー画面が表示されてしまいます。
※編集ができるように実装しましょう。

・削除ボタンを押すとエラー画面が表示されてしまいます。
※削除ボタンが押されたらトップページに戻るように実装しましょう。

修正が完了しましたら、再度以下のprotospace完了報告フォームのご提出お願いします！
※新しいissueを作っていただく必要はございません。
https://forms.gle/ZdLeprTTWhMA8aZA7
